// Generated by CoffeeScript 1.7.1
(function() {
    'use strict';
    angular.module('app.ui.ctrls', []).controller('footerctrl', [
            '$scope', '$modal', '$log', function($scope, $modal, $log) {
                $scope.items = ["item1", "item2", "item3"];
                $scope.open = function() {
                    var modalInstance;
                    modalInstance = $modal.open({
                        templateUrl: "myModalContent.html",
                        controller: 'ModalInstanceCtrl',
                        resolve: {
                            items: function() {
                                return $scope.items;
                            }
                        }
                    });
                    modalInstance.result.then((function(selectedItem) {
                        $scope.selected = selectedItem;
                    }), function() {
                        $log.info("Modal dismissed at: " + new Date());
                    });
                };
            }
        ]).controller('ModalInstanceCtrl', [
            '$scope', '$modalInstance', 'items', function($scope, $modalInstance, items) {
                $scope.items = items;
                $scope.selected = {
                    item: $scope.items[0]
                };
                $scope.ok = function() {
                    $modalInstance.close($scope.selected.item);
                };
                $scope.cancel = function() {
                    $modalInstance.dismiss("cancel");
                };
            }
        ])

}).call(this);
